### ISSUE TITLE
Model convert coreml2onnx error

### ISSUE THREAD

**Issue by psiydown** [AsuharietYgvar/AppleNeuralHash2ONNX#10]
Use the latest coreml2onnx.py convert other mlmodelc :

Error: Unsupported layer type: deconvolution line 507 
Prompt: deconvolution type is not supported. Hope to enhance it.

Valueerror: cannot reshape array of size 10752 into shape (672,4) line 415 
Need to change 4 to 16, but I wonder if this change is correct?

Finally, line 527, line 531-533, check_ model、inferred_ Model error, 
looking forward to solving it, you can contact us if necessary pmsy@qq.com Send model you test, thank you very much!

**Comment by ESAM-ALSAWAH** [comment]
hhhhh

**Comment by AsuharietYgvar** [comment]
Sorry for the super late reply. You should not use the latest coreml2onnx.py. Please follow the instructions in README and use the patched version of coreml2onnx.py.
